DATASETS = {
    "users": {
        "endpoint": "/internal/analytics/exports/users/",
        "watermark_field": "updated_at",
        "primary_key": "id",
        "write_disposition": "merge",
        "columns": {
            "id": {"data_type": "bigint"},
            "email": {"data_type": "text"},
            "first_name": {"data_type": "text"},
            "last_name": {"data_type": "text"},
            "is_active": {"data_type": "bool"},
            "is_staff": {"data_type": "bool"},
            "is_superuser": {"data_type": "bool"},
            "is_anonymous_signup": {"data_type": "bool"},
            "yesim_user_id": {"data_type": "text", "nullable": True},
            "stripe_customer_id": {"data_type": "text", "nullable": True},
            "merged_into_id": {"data_type": "bigint", "nullable": True},
            "merged_at": {"data_type": "timestamp", "nullable": True},
            "last_login": {"data_type": "timestamp", "nullable": True},
            "date_joined": {"data_type": "timestamp"},
            "created_at": {"data_type": "timestamp", "nullable": True},
            "updated_at": {"data_type": "timestamp"},
        },
    },
    "user_merges": {
        "endpoint": "/internal/analytics/exports/user-merges/",
        "watermark_field": "merged_at",
        "primary_key": "id",
        "write_disposition": "append",
        "columns": {
            "id": {"data_type": "text"},
            "anonymous_user_id": {"data_type": "bigint"},
            "authenticated_user_id": {"data_type": "bigint"},
            "sessions_transferred": {"data_type": "bigint"},
            "merged_at": {"data_type": "timestamp"},
        },
    },
    "sessions": {
        "endpoint": "/internal/analytics/exports/sessions/",
        "watermark_field": "updated_at",
        "primary_key": "id",
        "write_disposition": "merge",
        "columns": {
            "id": {"data_type": "text"},
            "user_id": {"data_type": "bigint", "nullable": True},
            "route": {"data_type": "text"},
            "click_id": {"data_type": "text"},
            "click_id_type": {"data_type": "text"},
            "ad_id": {"data_type": "text"},
            "adgroup_id": {"data_type": "text"},
            "campaign_id": {"data_type": "text"},
            "account_id": {"data_type": "text"},
            "utm_source": {"data_type": "text"},
            "utm_content": {"data_type": "text"},
            "user_agent": {"data_type": "text"},
            "ip_address": {"data_type": "text", "nullable": True},
            "app_code": {"data_type": "text"},
            "created_at": {"data_type": "timestamp"},
            "updated_at": {"data_type": "timestamp"},
        },
    },
    "orders": {
        "endpoint": "/internal/analytics/exports/orders/",
        "watermark_field": "updated_at",
        "primary_key": "id",
        "write_disposition": "merge",
        "columns": {
            "id": {"data_type": "text"},
            "user_id": {"data_type": "bigint"},
            "session_id": {"data_type": "text", "nullable": True},
            "status": {"data_type": "text"},
            "subtotal_eur": {"data_type": "text"},
            "discount_eur": {"data_type": "text"},
            "tax_eur": {"data_type": "text"},
            "total_eur": {"data_type": "text"},
            "subtotal_aed": {"data_type": "text", "nullable": True},
            "total_aed": {"data_type": "text", "nullable": True},
            "aed_rate_source": {"data_type": "text"},
            "billing_currency": {"data_type": "text"},
            "exchange_rate": {"data_type": "text", "nullable": True},
            "stripe_payment_intent_id": {"data_type": "text", "nullable": True},
            "stripe_checkout_session_id": {"data_type": "text", "nullable": True},
            "idempotency_key": {"data_type": "text"},
            "promo_code_id": {"data_type": "text", "nullable": True},
            "tax_rate_id": {"data_type": "bigint", "nullable": True},
            "tax_rate_percent": {"data_type": "text"},
            "app_code": {"data_type": "text"},
            "billing_country": {"data_type": "text"},
            "refund_amount_eur": {"data_type": "text"},
            "refund_amount_aed": {"data_type": "text"},
            "stripe_refund_id": {"data_type": "text", "nullable": True},
            "refunded_at": {"data_type": "timestamp", "nullable": True},
            "created_at": {"data_type": "timestamp"},
            "updated_at": {"data_type": "timestamp"},
        },
    },
    "order_line_items": {
        "endpoint": "/internal/analytics/exports/order-line-items/",
        "watermark_field": "created_at",
        "primary_key": "id",
        "write_disposition": "append",
        "columns": {
            "id": {"data_type": "text"},
            "order_id": {"data_type": "text"},
            "plan_id": {"data_type": "text"},
            "esim_id": {"data_type": "text", "nullable": True},
            "unit_price_eur": {"data_type": "text"},
            "unit_price_aed": {"data_type": "text"},
            "quantity": {"data_type": "bigint"},
            "line_total_eur": {"data_type": "text"},
            "line_total_aed": {"data_type": "text"},
            "plan_name": {"data_type": "text"},
            "plan_data_gb": {"data_type": "text"},
            "plan_days": {"data_type": "bigint"},
            "created_at": {"data_type": "timestamp"},
        },
    },
}

DEFAULT_LIMIT = 500
MAX_PAGES = 10000
REQUEST_TIMEOUT = 60
MAX_RETRIES = 3
RETRY_BACKOFF_BASE = 2
