# Maps each table to the field used to track the last pulled record.
TABLE_TO_FIELD_MAPPING = {
    "auth_user": ("id", None),
    "common_app": ("updated_at", None),
    "common_coupon": ("updated_at", None),
    "common_trackablepayload": ("created_at", None),
    "sso_appinstance": ("updated_at", None),
    "travel_animator_animationstate": ("updated_at", None),
    "travel_animator_annotation": ("id", None),
    "travel_animator_annotationmedia": ("id", None),
    "travel_animator_glbfile": ("id", None),
    "travel_animator_map": ("updated_at", {'map_json': {'data_type': 'json'}}),
    "travel_animator_marker": ("id", None),
    "travel_animator_routepoint": ("updated_at", None),
    "travel_animator_savedroute": ("updated_at", None),
    "travel_animator_texture": ("updated_at", None),
    "travel_animator_threedmodel": ("updated_at", None),
    "travel_animator_threedmodel_allowed_users": ("id", None),
    "travel_animator_usdzfile": ("id", None),
}
