name: Facebook Ads Daily ETL

on:
  workflow_dispatch:
  schedule:
    - cron: "10 1 * * *"  # Every day at 01:10 UTC

jobs:
  facebook_etl:
    strategy:
      matrix:
        group: [d1, m4, d2]
      fail-fast: false
    uses: ./.github/workflows/_reusable-etl.yml
    with:
      pipeline: facebook
      group: ${{ matrix.group }}
    secrets: inherit
