name: GA4-Daily-ETL
on:
  workflow_dispatch:
  schedule:
    - cron: "30 1 * * *"          # every day 01:30 UTC

jobs:
  etl:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        group: [d1]  # Add more groups as needed
      fail-fast: false            # one group failing won't cancel the rest

    env:
      GOOGLE_GROUPS: ${{ secrets.GOOGLE_GROUPS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Setup Secrets
        run: | 
          mkdir -p secrets
          echo "${{ secrets.SECRETS }}" | base64 --decode > .dlt/secrets.toml
          echo "${{ secrets.GOOGLE_GROUPS }}" | base64 --decode > secrets/google.json

      # Run only the subset for the current matrix entry
      - name: Run GA4 pipeline for ${{ matrix.group }}
        run: |
          python main.py 'google_analytics' '${{ matrix.group }}'
