name: Google-Ads-Manual-Backfill

on:
  workflow_dispatch:
    inputs:
      group:
        description: "Google Ads series/group (e.g., d1, or all)"
        type: choice
        required: true
        options:
          - d1
          - all
      days:
        description: "How many past days to backfill (e.g., 120)"
        type: string
        required: true

jobs:
  # Single group backfill
  backfill_one:
    if: ${{ inputs.group != 'all' }}
    runs-on: ubuntu-latest

    # Pass parameters into env vars consumed by the code
    env:
      # Used by setup step to materialize secrets
      GOOGLE_GROUPS: ${{ secrets.GOOGLE_GROUPS }}
      # Controls insights initial window in code at pipelines/google/sources.py
      GOOGLE_BACKFILL_DAYS: ${{ inputs.days }}
      # Ensures a unique dlt state directory so backfill doesn't reuse prior state
      PIPELINE_NAME_SUFFIX: _backfill_${{ inputs.group }}_${{ github.run_id }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Setup Secrets
        run: |
          mkdir -p secrets
          echo "${{ secrets.SECRETS }}" | base64 --decode > .dlt/secrets.toml
          echo "${{ secrets.GOOGLE_GROUPS }}" | base64 --decode > google.json

      - name: Run manual backfill for ${{ inputs.group }}
        run: |
          python main.py 'google' '${{ inputs.group }}'

  # All groups backfill in parallel
  backfill_all:
    if: ${{ inputs.group == 'all' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        group: [d1]
      fail-fast: false

    env:
      GOOGLE_GROUPS: ${{ secrets.GOOGLE_GROUPS }}
      GOOGLE_BACKFILL_DAYS: ${{ inputs.days }}
      PIPELINE_NAME_SUFFIX: _backfill_${{ matrix.group }}_${{ github.run_id }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Setup Secrets
        run: |
          mkdir -p secrets
          echo "${{ secrets.SECRETS }}" | base64 --decode > .dlt/secrets.toml
          echo "${{ secrets.GOOGLE_GROUPS }}" | base64 --decode > google.json

      - name: Run manual backfill for ${{ matrix.group }}
        run: |
          python main.py 'google' '${{ matrix.group }}'
