name: Run main.py every half hour

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Setup Secrets
        run: echo "${{ secrets.SECRETS }}" | base64 --decode > .dlt/secrets.toml

      - name: Connect to Lascade VPN
        uses: Jenin82/wiregaurd@v3
        with:
          config: ${{ secrets.WG_CONFIG_BASE64 }}

      - name: Run main.py
        run: python main.py
